### PR TITLE
Remove deprecated `ocio_config` `ImageIOConfigModel` settings

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Remove deprecated `ocio_config` `ImageIOConfigModel` settings

## Additional info

With [the support of profiles to determine OCIO config in ayon-core](https://github.com/ynput/ayon-core/pull/490) this logic has been superseded and should be removed from each addon still having the deprecated settings.

### CODE REVIEW

**Review by jakubjezek001 — COMMENTED** [review]
shouldn't defaults also be removed?

**Review by jakubjezek001 — APPROVED** [review]
Since no defaults are actually present then this is good to be merged

**Comment by BigRoy** [comment]
@iLLiCiTiT thanks for fixing :) saves me some time.

**Comment by BigRoy** [comment]
Ready to merge.

**Comment by iLLiCiTiT** [comment]
> @iLLiCiTiT thanks for fixing :) saves me some time.

It contains more commits than should, so I didn't fix it properly...

**Comment by BigRoy** [comment]
It's a thing of beauty @iLLiCiTiT ❤️

**Pull request merged**
