### PR TITLE
Fix frame range attributes for instances + validations

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

- Discard 'step' for pointcache/animation since it did not influence the output alembic at all.
- Default the frame range to current context task entity instead of current scene
- Add handle start and handle end attributes to be explicit about that, defaulting to current task attribs.
- Actually fix passing along the start and end frame to the Alembic export from creator to instance data.
- Add support for validating frame range against the instance's task/folder entity for review, pointcache, animation, etc. + support repair method for those.
- Remove redundant 'scene overrides' that tried to use that to affect what the alembic export did - but it didn't do much, and the export command has dedicated arguments for that.

## Additional info

I have no idea whether the `step` attribute does work for the other export methods, e.g. FBX or alike but we may need to double check that to see whether the `step` attribute is relevant anywhere.

Sorry for the big changes, but this really was way easier to fix when combining them.

## Testing notes:

The following product types should adhere to the frame ranges specified on the instances, be validated against the frame range (optionally) and when invalidated should allow repair to work.
1. [x] animation
2. [x] camera
3. [x] pointcache
4. [ ] render
5. [x] review

### CODE REVIEW

**Review by moonyuet — APPROVED** [review]
Did some simple test. Publish successfully with validate frame range.
image

Tested with incorrect frame range and repair action also works for fixing the frame range.
image

**Comment by BigRoy** [comment]
@LiborBatek any chance you can test the **render**?

**Review by LiborBatek — CHANGES_REQUESTED** [review]
First thanks for such a massive improvement / refactoring!!! Much appreciated...

It works well for most publish instance types!

The only malfunctioning is the ```Render``` as when validating the scene it doesnt take the values on the publish instance but global frame range (timeline at the bottom) this being also true when using ```Repair``` action as it tweaks the global timeline to correct values but not update the values on publish ```Render``` instance...

Seems like it somehow bypassing those instance frame range values atm.
Screenshot 2024-09-19 112647

**Comment by BigRoy** [comment]
Thanks @LiborBatek - should be fixed now. 

There was definitely a lot broken since the merge of #1

**Review by LiborBatek — APPROVED** [review]
Now it also works for ```Render``` publish instance...

LGTM!

**Pull request merged**
