### PR TITLE
Add switch asset support for all loaders inheriting from `BlenderLoader`

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Adds support for "Switch Asset" in scene inventory for blender loaders.

## Additional info

Based on comment [here](https://github.com/ynput/ayon-blender/pull/38#discussion_r1763243308)

## Testing notes:

1. Validate the 'switch' works as intended for managed Blender loaders

### CODE REVIEW

**Comment by moonyuet** [comment]
When I tries to do switch version from the same product type(in my case "model"), some errors pop up.
image
Making me wonder if we should introduce the switch version in blender, as it somehow involves the modifiers

**Comment by LiborBatek** [comment]
@moonyuet are u refering more to a ```Set Version``` as there is a ```Switch Folder``` not ```Version``` ...as Im experiencing issues with the ```Set Version``` atm in latest release of ayon-blender addon too

**Comment by moonyuet** [comment]
> @moonyuet are u refering more to a `Set Version` as there is a `Switch Folder` not `Version` ...as Im experiencing issues with the `Set Version` atm in latest release of ayon-blender addon too

I am more referring to the switch folder here but this is also related to `set version` in blender.

**Comment by BigRoy** [comment]
@moonyuet I think you're facing this issue https://github.com/ynput/ayon-blender/issues/40 - and hence it's not due to this PR.

**Review by LiborBatek — APPROVED** [review]
Works well...been tested on ```rig``` ```model``` and ```blendScene``` all working nicely!

B3d_switch_asset

**Pull request merged**
